apiVersion: v1
kind: Service
metadata:
  name: taiga-events
  namespace: taiga
spec:
  selector:
    io.kompose.service: taiga-events
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
