apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: taiga-async-rabbitmq-data
  name: taiga-async-rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
